### ISSUE TITLE
Published Velocity Coordinate Frame

### ISSUE THREAD

**Issue by kizilkayabayram** [enwaytech/reach_rs_ros_driver#4]
Does published velocity messages adhere any specific coordinate frame For example ROS uses forward-left-up and earth-north-up coordinate frames. But I haven't seen anything about velocity message's coordinates in source code. Does reach rs reports velocity in global frame?

**Comment by bochen87** [comment]
> Does published velocity messages adhere any specific coordinate frame For example ROS uses forward-left-up and earth-north-up coordinate frames. But I haven't seen anything about velocity message's coordinates in source code. Does reach rs reports velocity in global frame?

Hi, I guess this is more a product question that would be best asked in the product support forum at emlid: https://community.emlid.com/
